export function initContactSection(){const contactForm=document.getElementById('contactForm');const emailInput=document.getElementById('contact-email');const submitBtn=document.querySelector('.contact-submit-btn');const formStatus=document.getElementById('formStatus');const statNumbers=document.querySelectorAll('.contact-section .contact-stat-number');if(!contactForm)return;contactForm.addEventListener('submit',function(e){e.preventDefault();const email=emailInput.value.trim();if(!email||!isValidEmail(email)){showStatus('Please enter a valid email address.','error');return}
submitBtn.disabled=!0;submitBtn.innerHTML=`<span class="contact-btn-text">Sending...</span>`;setTimeout(()=>{const subject=encodeURIComponent('Early Access Request - Roopastra');const body=encodeURIComponent(`I would like to receive early access updates. My email: ${email}`);window.location.href=`mailto:info@roopastra.com?subject=${subject}&body=${body}`;showStatus('Thank you! Your email client should open.','success');emailInput.value='';resetSubmitButton();createCelebrationParticles()},1500)});function isValidEmail(email){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)}
function showStatus(message,type){formStatus.textContent=message;formStatus.className=`contact-form-status show ${type}`;setTimeout(()=>formStatus.classList.remove('show'),5000)}
function resetSubmitButton(){submitBtn.disabled=!1;submitBtn.innerHTML=`<span class="contact-btn-text">Notify Me</span>`}
emailInput.addEventListener('focus',()=>emailInput.parentElement.classList.add('focused'));emailInput.addEventListener('blur',()=>emailInput.parentElement.classList.remove('focused'));function animateCounters(){statNumbers.forEach(stat=>{if(stat.dataset.animated)return;stat.dataset.animated="true";const target=parseInt(stat.getAttribute('data-count'));const increment=target/100;let current=0;const timer=setInterval(()=>{current+=increment;if(current>=target){current=target;clearInterval(timer)}
stat.textContent=Math.floor(current)+(stat.dataset.suffix||'')},20)})}
const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){if(entry.target.classList.contains('contact-social-proof')){animateCounters()}
entry.target.classList.add('in-view')}})},{threshold:0.1});document.querySelectorAll('.contact-section .animated-on-scroll').forEach(el=>{observer.observe(el)});function createCelebrationParticles(){const colors=['#a855f7','#3b82f6','#10b981','#f59e0b'];for(let i=0;i<50;i++){const particle=document.createElement('div');particle.style.cssText=`
                position: fixed; width: 6px; height: 6px;
                background-color: ${colors[Math.floor(Math.random() * colors.length)]};
                border-radius: 50%; pointer-events: none; z-index: 9999;
                left: ${Math.random() * window.innerWidth}px;
                top: ${Math.random() * window.innerHeight}px;
            `;document.body.appendChild(particle);particle.animate([{transform:'translateY(0px) scale(0)',opacity:1},{transform:`translateY(-${Math.random() * 200 + 100}px) scale(1)`,opacity:1},{transform:`translateY(-${Math.random() * 300 + 200}px) scale(0)`,opacity:0}],{duration:2000,easing:'ease-out'}).onfinish=()=>particle.remove()}}
window.addEventListener('scroll',()=>{const scrolled=window.pageYOffset;const floatElements=document.querySelectorAll('.contact-section .contact-float-element');floatElements.forEach((element,index)=>{const speed=(index+1)*0.1;element.style.transform=`translateY(${scrolled * -speed}px)`})},{passive:!0})}