export function initHeroSection(){sidebarLinks.forEach(link=>{link.addEventListener('click',hideSidebar)});function initNavbar(){const navbar=document.querySelector(".navbar");let lastScrollY=window.scrollY;let ticking=!1;function updateNavbar(){const scrollY=window.scrollY;const scrollDirection=scrollY>lastScrollY?"down":"up";if(scrollY>50){navbar.classList.add("scrolled")}else{navbar.classList.remove("scrolled")}
if(!sidebar.classList.contains('active')){if(scrollDirection==="down"&&scrollY>200){navbar.style.transform="translateY(-100%)"}else if(scrollDirection==="up"){navbar.style.transform="translateY(0)"}}else{navbar.style.transform="translateY(0)"}
lastScrollY=scrollY<0?0:scrollY;ticking=!1}
window.addEventListener("scroll",()=>{if(!ticking){window.requestAnimationFrame(updateNavbar);ticking=!0}})}
document.addEventListener('DOMContentLoaded',initNavbar);function initHeroAnimations(){const heroElements={badge:document.querySelector(".glow-badge-wrapper"),titleLines:document.querySelectorAll(".title-line"),subtitleLines:document.querySelectorAll(".subtitle-line"),actions:document.querySelector(".hero-actions"),stats:document.querySelector(".hero-stats"),};const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("animate-in")}})},{threshold:0.1,});Object.values(heroElements).forEach((element)=>{if(element){if(NodeList.prototype.isPrototypeOf(element)){element.forEach((el)=>observer.observe(el))}else{observer.observe(element)}}})}
function initScrollAnimations(){const scrollElements=document.querySelectorAll("[data-scroll-reveal]");const scrollObserver=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("revealed")}else{entry.target.classList.remove("revealed")}})},{threshold:0.1,rootMargin:"0px 0px -50px 0px",});scrollElements.forEach((element)=>scrollObserver.observe(element));let ticking=!1;function updateParallax(){const scrolled=window.pageYOffset;const parallaxElements=document.querySelectorAll(".hero-background");parallaxElements.forEach((element)=>{const speed=0.5;element.style.transform=`translateY(${scrolled * speed}px)`});ticking=!1}
window.addEventListener("scroll",()=>{if(!ticking){requestAnimationFrame(updateParallax);ticking=!0}})}
function initParticleSystem(){const particleContainer=document.querySelector(".floating-particles");if(!particleContainer)return;const particleCount=12;for(let i=6;i<particleCount;i++){const particle=document.createElement("div");particle.className=`particle particle-${i + 1}`;particle.style.top=`${Math.random() * 100}%`;particle.style.left=`${Math.random() * 100}%`;particle.style.animationDelay=`${Math.random() * 8}s`;particle.style.animationDuration=`${6 + Math.random() * 4}s`;particleContainer.appendChild(particle)}
document.addEventListener("mousemove",(e)=>{const particles=document.querySelectorAll(".particle");const mouseX=e.clientX/window.innerWidth;const mouseY=e.clientY/window.innerHeight;particles.forEach((particle,index)=>{const speed=(index+1)*0.5;const x=(mouseX-0.5)*speed;const y=(mouseY-0.5)*speed;particle.style.transform=`translate(${x}px, ${y}px)`})})}
function initInteractiveElements(){const buttons=document.querySelectorAll(".get-started-btn, .watch-demo-btn, .nav-cta");buttons.forEach((button)=>{button.setAttribute("data-interactive","true");button.addEventListener("mouseenter",()=>{button.style.transform="translateY(-3px) scale(1.05)"});button.addEventListener("mouseleave",()=>{button.style.transform="translateY(0) scale(1)"});button.addEventListener("click",(e)=>{const ripple=document.createElement("span");const rect=button.getBoundingClientRect();const size=Math.max(rect.width,rect.height);const x=e.clientX-rect.left-size/2;const y=e.clientY-rect.top-size/2;ripple.style.cssText=`
                    position: absolute; width: ${size}px; height: ${size}px;
                    left: ${x}px; top: ${y}px; background: rgba(255, 255, 255, 0.3);
                    border-radius: 50%; transform: scale(0);
                    animation: ripple 0.6s ease-out; pointer-events: none;
                `;button.appendChild(ripple);setTimeout(()=>ripple.remove(),600)})});const style=document.createElement("style");style.textContent=`@keyframes ripple { to { transform: scale(4); opacity: 0; } }`;document.head.appendChild(style)}
function initTypingEffect(){const titleLines=document.querySelectorAll(".title-line");titleLines.forEach((line,index)=>{const text=line.textContent;line.textContent="";line.style.borderRight="2px solid #a855f7";setTimeout(()=>{typeText(line,text,50,()=>{setTimeout(()=>{line.style.borderRight="none"},500)})},index*1000)})}
function typeText(element,text,speed,callback){let i=0;const timer=setInterval(()=>{if(i<text.length){element.textContent+=text.charAt(i);i++}else{clearInterval(timer);if(callback)callback();}},speed)}
function initCounterAnimations(){const counters=document.querySelectorAll(".stat-number");const counterObserver=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){const counter=entry.target;const target=parseInt(counter.textContent.replace(/[^\d]/g,""));const suffix=counter.textContent.replace(/[\d]/g,"");animateCounter(counter,target,suffix,2000);counterObserver.unobserve(counter)}})});counters.forEach((counter)=>counterObserver.observe(counter))}
function animateCounter(element,target,suffix,duration){const start=0;const startTime=Date.now();const updateCounter=()=>{const elapsed=Date.now()-startTime;const progress=Math.min(elapsed/duration,1);const current=Math.floor(start+(target-start)*(1-Math.pow(1-progress,4)));element.textContent=current+suffix;if(progress<1){requestAnimationFrame(updateCounter)}};updateCounter()}
function initScrollIndicator(){const scrollIndicator=document.querySelector(".scroll-indicator");if(scrollIndicator){scrollIndicator.addEventListener("click",()=>{const nextSection=document.querySelector("section:not(#hero)");if(nextSection){nextSection.scrollIntoView({behavior:"smooth",})}});window.addEventListener("scroll",()=>{scrollIndicator.style.opacity=window.scrollY>100?"0":"1"})}}
initNavbar();initHeroAnimations();initScrollAnimations();initParticleSystem();initInteractiveElements();initTypingEffect();initCounterAnimations();initScrollIndicator();document.body.classList.add("loaded","animations-ready");function setViewportHeight(){const vh=window.innerHeight*0.01;document.documentElement.style.setProperty("--vh",`${vh}px`)}
window.addEventListener("resize",setViewportHeight);setViewportHeight();document.addEventListener("keydown",(e)=>{if(e.key==="Tab")document.body.classList.add("keyboard-navigation");});document.addEventListener("mousedown",()=>{document.body.classList.remove("keyboard-navigation")})}